version: "3.2"

services:
  mysqldb:
    image: gkmr/mysql-mecab
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3333:3306"
    cap_add:
      - SYS_NICE
    volumes:
     - mysql_data:/var/lib/mysql
    networks:
      - nestjs-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nestjs
    command: [ "sh", "scripts/start-api.sh" ]
    ports:
      - "5555:5555"
    depends_on:
      - mysqldb
    networks:
      - nestjs-network
    stdin_open: true
    tty: true

volumes:
  mysql_data:

networks:
  nestjs-network: null
